### ISSUE TITLE
tslrcm instructions are wrong I think

### ISSUE THREAD

**Issue by MrKiaser** [th3w1zard1/KOTORModSync#19]
Hello there old friend! I have a problem that is needed to fix well its that tslrcm instruction is wrong bc the instruction is saying I need a zip file but the offical relase have only a exe file rather than a zip one if there is a fix pls tell me

**Comment by th3w1zard1** [comment]
I have reuploaded the TSLRCM as a .zip with zbyl2's permission. This was done because the default TSLRCM installer is only available on windows and it requires clicking through a separate install screen.

The zips you need are provided with the instructions, but here's a direct link for you:
https://drive.google.com/drive/u/0/folders/156EqzmEESrxksm1f0cPl2tMUf-AOUt8Y

You could alternatively delete the instruction and install TSLRCM manually before attempting a KMS install.

**Comment by th3w1zard1** [comment]
Fixed by v0.8.3
