### ISSUE TITLE
Some files fail to validate despite having them downloaded+having the right file name

### ISSUE THREAD

**Issue by Enderlordalatreon** [th3w1zard1/KOTORModSync#31]
![Screenshot 2023-11-15 123145](https://github.com/th3w1zard1/KOTORModSync/assets/66154890/e3369dac-fb1b-4356-88d9-6a84d4d87877)
Error says that it couldn't find the exe in the Partyswap archive.
![Screenshot 2023-11-15 123326](https://github.com/th3w1zard1/KOTORModSync/assets/66154890/805026dc-812a-47bf-9672-69cd1a18c573)
Despite it being in the Archive
![Screenshot 2023-11-15 123702](https://github.com/th3w1zard1/KOTORModSync/assets/66154890/3a4d5693-cc71-4823-adfd-9ea77cb0b21f)
Every archive here has been downloaded, yet errors persist.
[kotormodsync_2023-11-15.log](https://github.com/th3w1zard1/KOTORModSync/files/13367632/kotormodsync_2023-11-15.log)
Log

**Comment by Enderlordalatreon** [comment]
Very strange, I've redownloaded every mod but from alternate links (ModDB, Nexus) rather than deadlystream (as the neocities site, and by extension modsync, links to) and everything went well. I had to download the 1.1.3 version of PartySwap off of ModDB rather than the 1.3.4 version off of deadlystream. I wonder what the issue is.

**Comment by th3w1zard1** [comment]
> Very strange, I've redownloaded every mod but from alternate links (ModDB, Nexus) rather than deadlystream (as the neocities site, and by extension modsync, links to) and everything went well. For example, I had to download the 1.1.3 version of PartySwap off of ModDB rather than the 1.3.4 version off of deadlystream. Another example is "Handmaiden and Female Exile - Disciple and Male Exile Romance" needing to be downloaded off Nexus instead of deadlystream, probably due to file name shenanigans. I wonder if the neocities list is outdated?

So the main problem is mod's release updates. If they change their filenames around too much, the wildcards the instruction files are using can't match the new filenames. Most of the time, the new versions are compatible, but the instruction needs updating.

For example if it's looking for a `K1_Community_Patch_v*.zip` it'll match `K1_Community_Patch_v1.10.zip` and `K1_Community_Patch_v1.9.2.zip` But if a mod changes to, say, `KOTOR1_COMMUNITY_PATCH_version1.10.zip` you'll need to simply edit that archive name in the gui editor. There's not much I can do but hope that mod developers will notify me when they update their mod.

The neocities encounters the same problem, but due to the large community backing they're more likely to update their instructions before I can. I am a solo dev working on this by myself.

Thank you for reaching out, I'll update the mods according to your log file as soon as I get a chance. Please reach out if you have any more issues.

**Comment by th3w1zard1** [comment]
> For example, I had to download the 1.1.3 version of PartySwap off of ModDB rather than the 1.3.4 version off of deadlystream.

The latest version I was aware of is 1.3.3.

**Comment by th3w1zard1** [comment]
Looking more closely at your logs, it seems you did not set your mod directory correctly. You need to download your mods, unextracted, to the mod directory. Let KOTORModSync do all the extracting/installing for you.

**Comment by th3w1zard1** [comment]
stale
