### ISSUE TITLE
Few mods fail install in modsync, but manual install is successful

### ISSUE THREAD

**Issue by iMakedonsky** [th3w1zard1/KOTORModSync#34]
Toml file
[my_toml_instructions.zip](https://github.com/th3w1zard1/KOTORModSync/files/13799406/my_toml_instructions.zip)

Taris dueling ring
![image](https://github.com/th3w1zard1/KOTORModSync/assets/13186918/6b0a14bf-7df5-4176-b1b9-32778af7a62a)

Kill czerka jerk
![image](https://github.com/th3w1zard1/KOTORModSync/assets/13186918/0f496eef-30b4-4415-a213-41543281b71f)

Shanilla
![image](https://github.com/th3w1zard1/KOTORModSync/assets/13186918/023cd584-021c-45b2-98c6-3033c4d7fc37)

When I've rerun TSLpatchers of all these mods manually after the install, they finished successfully.

**Comment by th3w1zard1** [comment]
The first mod looks like the validators failed to find the problem with the instructions. The validators only (currently) validate files in an archive, and that mod is not in an archive. The branch `better-validators` is an attempt to dry-run the whole instruction set but the code is not ready for merge.

The second mod actually installed correctly. Looks like there was some issue with nwnnsscomp.exe. It used the built-in compiler (PyKotor's knsscomp compiler) as a fallback and ended up compiling it successfully. Not sure why it's failing atm since it is a part of the modbuild and has worked in all of my tests in the past.

The third mod looks like there's an issue with HoloPatcher. If you could post an issue with the `installlog.txt` for that mod on https://github.com/NickHugi/PyKotor that would be great.

This has been an initial review, I'll take a look at these more in detail as soon as possible. Thanks for reporting these bugs.

**Comment by iMakedonsky** [comment]
> Can you post your kms log file please?
> 
> The first mod looks like the validators failed to find the problem with the instructions. The validators only (currently) validate files in an archive, and that mod is not in an archive. The branch `better-validators` is an attempt to dry-run the whole instruction set but the code is not ready for merge.
> 
> The second mod actually installed correctly. Looks like there was some issue with nwnnsscomp.exe. It used the built-in compiler (PyKotor's knsscomp compiler) as a fallback and ended up compiling it successfully. Not sure why it's failing atm since it is a part of the modbuild and has worked in all of my tests in the past.
> 
> The third mod looks like there's an issue with HoloPatcher. If you could post an issue with the `installlog.txt` for that mod on https://github.com/NickHugi/PyKotor that would be great.
> 
> This has been an initial review, I'll take a look at these more in detail as soon as possible. Thanks for reporting these bugs.

Sorry, Not sure what kms log file means.

Will look for installog.txt now though

Thanks for the response!

**Comment by th3w1zard1** [comment]
I believe the last release (1.1.0b2) should fix the last two mods that were erroring here.
